telegram-cli -W -e "msg @LvanLamCommitCodeBot /jdcrazyjoy wIgzEM1_9ferfc3eWGgXhA=="
telegram-cli -W -e "msg @LvanLamCommitCodeBot /jdzz S4KQmQR9CsAo"
telegram-cli -W -e "msg @LvanLamCommitCodeBot /jdcash fUJibe3pI6I"
telegram-cli -W -e "msg @TuringLabbot /submit_activity_codes bean wcc4dypma3lqgyfoff23i4gzai"
telegram-cli -W -e "msg @TuringLabbot /submit_activity_codes farm 77d80c6b738948a0a5cc9f01b34aca2d"
telegram-cli -W -e "msg @TuringLabbot /submit_activity_codes pet MTE1NDQ5OTUwMDAwMDAwNDY3NTc5ODE="
telegram-cli -W -e "msg @TuringLabbot /submit_activity_codes ddfactory T0114KQmQR9CsAoCjVWnYaS5kRrbA"
telegram-cli -W -e "msg @TuringLabbot /submit_activity_codes jxfactory 0VAqzh6CGrQDSTqgK7yu_Q=="
telegram-cli -W -e "msg @TuringLabbot /submit_activity_codes sgmh T0114KQmQR9CsAoCjVQmoaT5kRrbA"
telegram-cli -W -e "msg @TuringLabbot /submit_activity_codes jxcfd C95C2793BF86E739FA825E43E3B98C09D815603E8D5D679FE70E6C53AB8F2844"
